version: 2.1

jobs:
  build0:
    docker:
      - image: harbor.cyverse.org/vice/jupyter/tensorflow:latest
    steps:
      - checkout
      - run: jupyter lab --version
  build1:
    docker:
      - image: harbor.cyverse.org/vice/jupyter/tensorflow:2.2.9
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: harbor.cyverse.org/vice/jupyter/tensorflow:geospatial
    steps:
      - checkout
      - run: jupyter lab --version
 
workflows:
  build:
    jobs:
      - build0
      - build1
      - build2
